#!/usr/bin/env bash
set -eux

npm ci

: Optional tag argument
TAG=

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag=*)
      TAG="${1#*=}"
      shift
      ;;
    *)
      echo "Unknown argument: $1"
      echo "Usage: ./scripts/build-next [--tag=TAG_NAME]"
      exit 1
      ;;
  esac
done

: Update the package.json version before build and publish
node ./scripts/update-version.mjs utils $TAG
node ./scripts/update-version.mjs zod-schemas $TAG
node ./scripts/update-version.mjs nns-proto $TAG
node ./scripts/update-version.mjs ledger-icp $TAG
node ./scripts/update-version.mjs ledger-icrc $TAG
node ./scripts/update-version.mjs nns $TAG
node ./scripts/update-version.mjs sns $TAG
node ./scripts/update-version.mjs cmc $TAG
node ./scripts/update-version.mjs ckbtc $TAG
node ./scripts/update-version.mjs cketh $TAG
node ./scripts/update-version.mjs ic-management $TAG

: Now we can build
npm run build --workspaces
