#!/usr/bin/env bash
set -eux

npm ci

: Update the package.json version before build and publish
node ./scripts/update-version.mjs utils
node ./scripts/update-version.mjs zod-schemas
node ./scripts/update-version.mjs nns-proto
node ./scripts/update-version.mjs ledger-icp
node ./scripts/update-version.mjs ledger-icrc
node ./scripts/update-version.mjs nns
node ./scripts/update-version.mjs sns
node ./scripts/update-version.mjs cmc
node ./scripts/update-version.mjs ckbtc
node ./scripts/update-version.mjs cketh
node ./scripts/update-version.mjs ic-management

: Now we can build
npm run build --workspaces
