#!/usr/bin/env bash
set -eux

npm ci

: Update the package.json version before build and publish
node ./scripts/update-version.mjs utils
node ./scripts/update-version.mjs ledger
node ./scripts/update-version.mjs nns
node ./scripts/update-version.mjs sns
node ./scripts/update-version.mjs cmc
node ./scripts/update-version.mjs ckbtc

: Now we can build
npm run build --workspaces
