#!/usr/bin/env bash

function rm_agent() {
  local package=$1

  npm rm @icp-sdk/core --workspace=packages/"$package"

  # Just in case, make sure the dependencies re-exported by `@icp-sdk/core` are properly removed
  npm rm @dfinity/agent @dfinity/candid @dfinity/principal @dfinity/identity @dfinity/identity-secp256k1 --workspace=packages/"$package"
}

function install_agent() {
  local package=$1

  npm i @icp-sdk/core@latest --workspace=packages/"$package" --save-peer
}

PACKAGES=utils,ckbtc,cketh,cmc,ic-management,ledger-icp,ledger-icrc,nns,sns,zod-schemas,canisters

# Remove agent-js libraries from all packages first to avoid resolve conflicts between those
for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  rm_agent "$package"
done

for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  install_agent "$package"
done
