#!/usr/bin/env bash

function rm_agent() {
  local package=$1

  npm rm @dfinity/agent @dfinity/candid @dfinity/principal --workspace=packages/"$package"
}

function install_agent() {
  local package=$1

  npm i @dfinity/agent@beta @dfinity/candid@beta @dfinity/principal@beta --workspace=packages/"$package" --save-peer
}

function install_principal() {
  local package=$1

  npm i @dfinity/principal@beta --workspace=packages/"$package" --save-peer
}

PACKAGES=utils,ckbtc,cketh,cmc,ic-management,ledger-icp,ledger-icrc,nns,sns

PACKAGES_PRINCIPAL_ONLY=zod-schemas

# Remove agent-js libraries from all packages first to avoid resolve conflicts between those
for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  rm_agent "$package"
done

for package in $(echo $PACKAGES_PRINCIPAL_ONLY | sed "s/,/ /g"); do
  rm_agent "$package"
done

for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  install_agent "$package"
done

for package in $(echo $PACKAGES_PRINCIPAL_ONLY | sed "s/,/ /g"); do
  install_principal "$package"
done
