# A GitHub Actions workflow that generates the documentation for pull requests

name: Documentation

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Generate docs
        run: npm run docs

      - name: Commit docs
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actions
          message: "🤖 Documentation auto-update"