name: Next Publication

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'npm tag to publish under'
        required: true
        default: 'next'
        type: choice
        options:
          - next
          - beta

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build version for tag
        run: ./scripts/build-next --tag=${{ inputs.tag }}

      - name: Publish utils
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/utils
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish Ledger ICRC
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/ledger-icrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish Ledger ICP
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/ledger-icp
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish NNS-proto
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/nns-proto
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish NNS
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/nns
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish SNS
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/sns
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish CMC
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/cmc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish ckBTC
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/ckbtc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish ckETH
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/cketh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish ic-management
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/ic-management
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish Zod schemas
        run: npm publish --provenance --tag ${{ inputs.tag }} --workspace=packages/zod-schemas
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
