name: CI Checks

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build nightly
        run: ./scripts/build-nightly
      - name: Publish
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
