name: Next Publication

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build next version
        run: ./scripts/build-next
      - name: Set up npm
        run: printf '%s\n' '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' registry=https://registry.npmjs.org/ always-auth=true >> .npmrc
      - name: Publish utils
        run: npm publish --provenance --tag next --workspace=packages/utils
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish Ledger
        run: npm publish --provenance --tag next --workspace=packages/ledger
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish NNS-proto
        run: npm publish --provenance --tag next --workspace=packages/nns-proto
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish NNS
        run: npm publish --provenance --tag next --workspace=packages/nns
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish SNS
        run: npm publish --provenance --tag next --workspace=packages/sns
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish CMC
        run: npm publish --provenance --tag next --workspace=packages/cmc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish ckBTC
        run: npm publish --provenance --tag next --workspace=packages/ckbtc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
